// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // קובץ זה משמש אך ורק את ה-CLI של Prisma (migrations וכו'), ולא את
    // האפליקציה בזמן ריצה. ה-Transaction Pooler (פורט 6543) אינו תומך
    // ב-migrations ומוביל לתקיעה, ולכן ה-CLI עובד תמיד מול החיבור הישיר
    // (Session Pooler, פורט 5432). האפליקציה עצמה משתמשת ב-DATABASE_URL
    // הרגיל - ראו src/lib/prisma.ts.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
